---
plugin: aws_ec2

aws_profile: roman_avseenko

regions:
  - 'us-east-2'

filters:
  tag:Project:
    - DevOpsLab
  instance-state-name : running
keyed_groups:
  - key: tags.Name
    separator: ''
...

